version: '3'

services:
  web:
    build: .
    command: gunicorn -w 4 -b 0.0.0.0:5500 app:app
    ports:
      - "5500:5500"
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
